### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by muhassin-eps** [Jason-Rev/vscode-spell-checker#316] opened 2019-03-21 12:18 UTC
[streetsidesoftware.code-spell-checker-unresponsive.cpuprofile.txt](https://github.com/Jason-Rev/vscode-spell-checker/files/2992029/streetsidesoftware.code-spell-checker-unresponsive.cpuprofile.txt)
- Issue Type: `Performance`
- Extension Name: `code-spell-checker`
- Extension Version: `1.6.10`
- OS Version: `Linux x64 4.4.0-142-generic`
- VSCode version: `1.32.3`

:warning: Make sure to **attach** this file from your *home*-directory: `/home/eps63/streetsidesoftware.code-spell-checker-unresponsive.cpuprofile.txt` :warning:

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by zsolt-dev** [comment] 2019-04-03 14:56
same here... disabled all plugins and enabled each separately to isolate which one is causing the high cpu. 

Thank you for the great plugin, but I have it disabled until it is fixed. Just reporting...

**Comment by Jason3S** [comment] 2019-04-29 20:00
@zsolt-dev does this still happen after the update to 1.7.6?

**Comment by Jason3S** [comment] 2019-04-29 20:01
Duplicate of #309

**Closed by Jason3S** 2019-04-29 20:01 UTC
Labels: duplicate
