### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by parvezq** [Jason-Rev/vscode-spell-checker#310] opened 2019-03-14 07:27 UTC
- Issue Type: `Performance`
- Extension Name: `code-spell-checker`
- Extension Version: `1.6.10`
- OS Version: `Darwin x64 18.0.0`
- VSCode version: `1.32.2`

:warning: Make sure to **attach** this file from your *home*-directory: `/Users/admin/streetsidesoftware.code-spell-checker-unresponsive.cpuprofile.txt` :warning:

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by AlekSi** [comment] 2019-03-15 05:23
Dupe of #303?

**Comment by Jason3S** [comment] 2019-03-15 19:41
@parvezq would you please attach the file? `streetsidesoftware.code-spell-checker-unresponsive.cpuprofile.txt`

**Comment by Jason3S** [comment] 2019-04-29 19:58
Dupe of #309

**Closed by Jason3S** 2019-04-29 19:58 UTC
Labels: duplicate
