### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by lkevinzc** [Jason-Rev/vscode-spell-checker#328] opened 2019-04-18 06:48 UTC
- Issue Type: `Performance`
- Extension Name: `code-spell-checker`
- Extension Version: `1.6.10`
- OS Version: `Darwin x64 18.5.0`
- VSCode version: `1.33.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`/Users/zichen.liu/streetsidesoftware.code-spell-checker-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by Jason3S** [comment] 2019-04-18 15:52
Please attach the file. It is very difficult for me to hunt down the issue if the file is not attached.

**Comment by Jason3S** [comment] 2019-04-29 19:59
Dupe of #309

**Closed by Jason3S** 2019-04-29 19:59 UTC
Labels: duplicate
