### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by CesarAugustoBispo** [Jason-Rev/vscode-spell-checker#321] opened 2019-04-07 19:22 UTC
- Issue Type: `Performance`
- Extension Name: `code-spell-checker`
- Extension Version: `1.6.10`
- OS Version: `Linux x64 4.15.0-47-generic`
- VSCode version: `1.33.0`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`/home/cesar/streetsidesoftware.code-spell-checker-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by Jason3S** [comment] 2019-04-29 19:59
Dupe of #309

**Closed by Jason3S** 2019-04-29 19:59 UTC
Labels: duplicate
