### ISSUE TITLE
\nwas will be recognized as 'nwas'

### ISSUE THREAD

**Issue by jens1o** [Jason-Rev/vscode-spell-checker#31] opened 2016-11-28 13:38 UTC
![image](https://cloud.githubusercontent.com/assets/11234139/20670227/47d5ed84-b578-11e6-9ba2-05807590ea57.png)

As you may see there, explicit newlines won't be caught.

**Comment by Jason3S** [comment] 2016-11-28 13:51
Thank you @jens1o .   Nice example image.  This is a duplicate of #7.

**Comment by Jason3S** [comment] 2017-01-08 15:33
This should be fixed with 0.14.0

**Closed by Jason3S** 2017-01-08 15:33 UTC
Labels: bug, Done / Fixed, duplicate

**Comment by jens1o** [comment] 2017-01-08 17:36
God bless you! That's a big help!
