### ISSUE TITLE
Maximal number of problems

### ISSUE THREAD

**Issue by urob** [Jason-Rev/vscode-spell-checker#172] opened 2018-01-18 23:35 UTC
First of all, thanks for such a great extensions.

I noticed a limitation when playing around with the maximal number of problems setting ("cSpell.maxNumberOfProblems"). Regardless of its configuration, the maximal number of problems remains restricted by the upper bound of 250 problems that is hardcoded into vs code. In large documents with lots of names this can become easily binding, preventing further spellchecking unless one adds all into a personal dictionary. I don't know if this is feasible, but it would be nice to see a workaround around the somewhat restrictive behavior of vs code.

**Comment by Jason3S** [comment] 2018-01-19 07:53
Thank you for the feedback.

Let us start with what are you trying to do? If I understand what you are trying to do, then I can maybe make some suggestions on how it could be fixed.

If you want a log of the spelling errors, try installing the command line tool [cspell](https://www.npmjs.com/package/cspell).

**Comment by urob** [comment] 2018-01-19 17:23
Thanks for getting back! I am using it as a language spellchecker for latex documents. I don't care much for the list of problems in the problems tab, but would like to visually indicate misspelled words throughout the document (marked by the wiggly red underline by default). Currently, it only marks the first 250 misspelled words, regardless of the setting for "cSpell.maxNumberOfProblems".

**Comment by Bludkey** [comment] 2018-01-21 13:33
The problem is that with LaTex some keywords are not recognized, than there are likely lots of names or terms in your document, and you quickly exceed max number of warnings
  (from this extension) in VS Code: 
![image](https://user-images.githubusercontent.com/27734159/35194708-dcf5278e-feb7-11e7-96f1-24b661ba4286.png)
![image](https://user-images.githubusercontent.com/27734159/35194627-90cc3074-feb6-11e7-8622-02e1f569d6b9.png)

**Comment by Jason3S** [comment] 2018-01-21 17:42
Do you have a sample doc I can use to improve the LaTex support?

**Comment by Bludkey** [comment] 2018-01-27 17:58
It is not that simple and I said it maybe unclearly.
There are more than 3000 packages and every package consist of several macros. Some macros have not been recognized. To add all these macros to dictionary would be very hard work even than there are parameters that not correspond with camelCase or any other, theyarejustlikethis. 


What could work:

1. Escape all macro's names: All macros start with `\` and end with space or `\` or it have parameters in `{}` or `[]`.  This probably break the first idea of this project - to check spelling in variable/function names and comments, but for LaTeX only purpose this could be reasonable (you want check mainly the text)![image](https://user-images.githubusercontent.com/27734159/35474761-f234947e-0392-11e8-9710-0cd20fa8bd26.png)
2. Escape parameters which contain `=`. Parameters of this format are probably setups.![image](https://user-images.githubusercontent.com/27734159/35474736-af58d354-0392-11e8-9414-76fae80de630.png)
3. Escape parameters of `\usepackage` macro and maybe some other macros (for citations)
![image](https://user-images.githubusercontent.com/27734159/35474771-31aafbd4-0393-11e8-856f-d1dc953ffaf5.png)


Like this
![image](https://user-images.githubusercontent.com/27734159/35474817-df5ad092-0393-11e8-90a3-1f256e95dc1f.png)

`
         \EscapeThisdamnmacro{SpellCheckThisParameter}{
             DoNottrythat=here,
             Norhere=no} %same with parameters within []
`

**Comment by Bludkey** [comment] 2018-01-27 18:03
*Maybe we should put this in new thread

**Comment by urob** [comment] 2018-01-28 02:27
Regarding the escaping of latex commands, the author of Latex-workshop recommends using the following ignore pattern to prevent cspell from checking them:
    "cSpell.ignoreRegExpList": [
        "\\\\\\w*(\\[.*?\\])?(\\{.*?\\})?",
        "\\$.+?\\$"
    ]

For me this works great, succeeding in cspell only checking the actual writing. But still, with technical reports that involve many non-dictionary terms, one can quickly exceed 250 errors, after which the remainder of the text remains unchecked. Hence my initial request.

**Comment by Jason3S** [comment] 2018-01-28 07:41
Ok, so LaTex is the language.

Even though we cannot change the number of issues shown by VS Code, we might be able to do something about the issues themselves.

**Comment by Bludkey** [comment] 2018-02-18 15:29
Oh, I miss this note in Latex workshop description. 

It would be great to incorporate some ignore regexp to Latex spell check. Thus this would be the default for LaTeX documents.

I have done IHMO bit better ignore pattern (than mentioned above):
`\\\w+(?:\[[^]*?\]|\{[^]*?\})*`

**Comment by Jason3S** [comment] 2018-02-18 15:33
Nice, I'll try it out.

**Comment by Bludkey** [comment] 2018-02-18 16:21
You asked for sample doc. You can use [this](https://www.overleaf.com/13871258hsfhjdsgsngt#/53744876/) on Overleaf (online LaTeX editor)
![overleaf](https://user-images.githubusercontent.com/27734159/36354084-3b669974-14cf-11e8-865c-2dd97569511a.gif)

**Comment by Jason3S** [comment] 2019-05-07 09:26
I'm going to close this for now. LaTex support has been improved since this issue was created. If you see more problems, please create a new issue and refer to this one.

**Closed by Jason3S** 2019-05-07 09:26 UTC
