### ISSUE TITLE
Switching to en-GB dictionary still accepts American English

### ISSUE THREAD

**Issue by BillDenton** [Jason-Rev/vscode-spell-checker#74] opened 2017-03-03 11:35 UTC
After adding setting:
    "cSpell.language": "en-GB"
the spelling color is still accepted. I tried commenting out the setting and starting again and it then accepted colour.
However on another PC it correctly marked color as a mistake, but then suggested color as acceptable in the list (color, colon, colour, etc)

**Comment by Jason3S** [comment] 2017-03-03 14:19
I am guessing you might need up update the Spell Checker extension.  Can you check the version?

**Comment by BillDenton** [comment] 2017-03-03 14:58
There's something strange going on. On my laptop the extension is on 0.17.2, but on my desktop is stuck on 0.14.8. After uninstalling and reinstalling the extension it is now 0.17.2.  However, this hasn't fixed the issue. I also noticed that I had "color" in the "cSpell.flagWords" list. After removing it was accepted as valid. So there appears to be two issues:
1. Either it isn't switching dictionaries or the GB dictionary has "color" in it.
2. Words in the flagWords list are being offered as spelling corrections. I have confirmed this by adding "these" to the list. "these" was marked as a spelling mistake, and top of the list of suggestions was these.

**Comment by Jason3S** [comment] 2017-03-07 20:43
There are two different issues here.

1. **Color** is appearing even though it is not a British English word.
    Even though **color** is not in the British English dictionary, it is in other dictionaries like CSS and HTML.  Depending upon the type of file you are editing, different dictionaries are loaded.  This can cause American english words to be included because they are valid keywords.

2. Words in the forbidden list are being suggested (because the are in one of the active dictionaries).
    This is a valid issue.  It is a bit strange from a usability perspective.  The issue is that forbidden words are not filtered out of the suggestion list before it is presented.  If you think this is a big issue, please create a new issue.  It is a perfect candidate for a pull request.

**Comment by arthur-st** [comment] 2017-09-12 11:07
Same issue, 1.3.9 extension running on VSCode 1.16 (x64).

**Comment by Jason3S** [comment] 2017-09-12 20:15
What `language local` does it show when you right click in your `.tex` document and choose `Show Spell Checker Configuration Info`?
![image](https://user-images.githubusercontent.com/3740137/30345764-a3fe2f06-9806-11e7-9553-0afbaa7b88a4.png)

![image](https://user-images.githubusercontent.com/3740137/30345825-f245c246-9806-11e7-8825-1de60299da86.png)

or

![image](https://user-images.githubusercontent.com/3740137/30345834-033801fe-9807-11e7-8520-38de6fc84927.png)

or

![image](https://user-images.githubusercontent.com/3740137/30345857-14b9c75a-9807-11e7-8053-1a790a1c7420.png)

**Comment by svasil** [comment] 2017-12-12 11:09
Visual Studio Code 1.18.1 x64
Code Spell Checker 1.6.0

not able to activate en-gb after any manipulations with setup, dictionary always disabled.
What should I do?

**Comment by Jason3S** [comment] 2017-12-12 11:21
There is a bug in VS Code that caches old settings. You have to restart VS Code. ☹️ 

Once the setting has been set, it will be possible to change it with the UI.

**Comment by svasil** [comment] 2017-12-12 11:55
So what should I do?

I updated "cSpell.language": "en,en-GB", I have exit VS Code. Start again, open MarkDown file and I see that I don't have active en-Gb dictionary
![image](https://user-images.githubusercontent.com/8158755/33883295-8f055ddc-df3b-11e7-8388-84116b9ae622.png)
![image](https://user-images.githubusercontent.com/8158755/33883314-a71fd564-df3b-11e7-8342-6b8ee7808d55.png)

**Comment by Jason3S** [comment] 2017-12-12 12:28
It is acting like another cspell.json file is blocking the setting.

Try turning on / off **Folder** settings and toggle the en_GB value.

This should clear local cspell.json files. If that does not work, look for a cspell.json file in the workspace folders. It can be at the root of the folder or inside .vscode.

**Comment by svasil** [comment] 2017-12-12 12:58
I have played with switch off/on — no reaction.

I have found two cspell.json
![image](https://user-images.githubusercontent.com/8158755/33885691-5d255cb4-df44-11e7-900a-e4c1659e87b1.png)

Content is
// cSpell Settings
{
    // Version of the setting file.  Always 0.1
    "version": "0.1",
    // language - current active spelling language
    "language": "en",
    // words - list of words to be always considered correct
    "words": [
        "mkdirp",
        "tsmerge",
        "githubusercontent",
        "streetsidesoftware",
        "vsmarketplacebadge",
        "visualstudio",
        "languageclient",
        "langs"
    ],
    // flagWords - list of words to be always considered incorrect
    // This is useful for offensive words and common spelling errors.
    // For example "hte" should be "the"
    "flagWords": [
        "hte"
    ]
}

and
// cSpell Settings
{
    // Version of the setting file.  Always 0.1
    "version": "0.1",
    // language - current active spelling language
    "language": "en",
    // words - list of words to be always considered correct
    "words": [
        "Pausable",
        "Observables",
        "Streamable"
    ],
    // flagWords - list of words to be always considered incorrect
    // This is useful for offensive words and common spelling errors.
    // For example "hte" should be "the"
    "flagWords": [
        "hte"
    ]
}

which of them should I edit and how?

**Comment by Jason3S** [comment] 2017-12-14 10:56
@svasil Those files do not need to be changed.

Can you make sure you do not have any errors in your settings.json files?

The best way is to open VS Code settings and look for any errors.

![image](https://user-images.githubusercontent.com/3740137/33988785-c0be11b2-e0c5-11e7-81ec-8c066ea23053.png)

**Comment by svasil** [comment] 2017-12-14 11:31
I have message "No problems have been detected"

**Comment by Jason3S** [comment] 2017-12-17 21:46
I am a bit stumped on why it is not working for you. When I get the chance, I'll try adding some more logs to help with hunting down this sort of issue.

**Comment by svasil** [comment] 2017-12-18 08:55
Problem was solved in VS Code 1.19.0

**Comment by Jason3S** [comment] 2017-12-18 13:36
@svasil Great to hear!

**Comment by Jason3S** [comment] 2018-02-22 21:26
@BillDenton I'm going to close this issue for now.

**Closed** 2018-02-22 21:26 UTC
Labels: enhancement
